### ISSUE TITLE
Need SNMP Generator YAML

### ISSUE THREAD

**Issue by tico88612** [zorrzoor/grafana-idrac-dashboard#1]
Nice YAML file & Dashboard, thank you!

but I have one question, how do you generate your snmp.yaml?

**Comment by zorrzoor** [comment]
To generate `snmp.yaml` please checkout [Generator](https://github.com/prometheus/snmp_exporter/tree/main/generator)

or just use the default `snmp.yaml` from [snmp_exporter](https://github.com/prometheus/snmp_exporter/blob/main/snmp.yml)

**Comment by tico88612** [comment]
@zorrzoor Thanks for your reply.

I knew SNMP Generator, but it needs `generator.yml`, I didn't see any about dell idrac in default `generator.yml` file.

Can you provide your `generator.yml`? thank you.

**Comment by zorrzoor** [comment]
Aha, sorry.
I currently only have Dell idrac stuff in my `generator.yml` file.
What you can do is create your `snmp.yml` with the generator and then just add the lines from my [snmp.yml](snmp.yml)

I'll also upload my `generator.yml` later this weekend and add notify you here.

I'm also working on a pull request towards `snmp generator` to add Dell idrac.
But that is currently on hold due to work.

**Comment by zorrzoor** [comment]
`generator.yml` file added
